num_behaviors: null
concurrency_limit: 20

max_turns: 5
max_epochs: 50

independent_judge: true
independent_judge_config:
  model: gpt-4o
  provider: openai
  judge_types: [XTeaming, ChainOfAttack, FootInTheDoor]
  majority_vote_threshold: 3

attack_type: XTeaming
attack_config:
  attacker_model: &shared_model
    model: Qwen/Qwen2.5-32B-Instruct
    provider: local
    base_url: http://10.100.0.0:30000/v1
  judge_model:
    model: gpt-4o
    provider: openai
  textgrad_engine_model: *shared_model
  max_refines_per_turn: 3
  num_sets: 1
  use_multiple_strategies: true

target_config:
  model: meta-llama/Meta-Llama-3-70B-Instruct
  provider: local
  base_url: http://10.100.0.0:30000/v1